server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discoveryms

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false